app:
  name: "web_app"
  mode: "dev"
  port: 8088

log:
  level : "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
 host: "60.191.116.77"
 prot: 3306
 user: root
 password: "qwert"
 dbname: "sql_demo"
 max_open_conns : 200
 max_idle_conns : 50
redis:
  host: "127.0.0.1"
  password: "qwerty"
  port: 6379
  db: 0
  pool_size: 100