name: "web_app"
mode: "dev"
port: 8080
version: "v0.1.4"
log:
  level : "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
 host: "60.191.116.77"
 port: 3306
 user: "root"
 password: "qwert"
 dbname: "bulebell"
 max_open_conns : 200
 max_idle_conns : 50
redis:
  host: "192.168.4.80"
  password: "qwerty"
  port: 6379
  db: 0
  pool_size: 100